#############################################################################
# Makefile for building: ../bin/test05.app/Contents/MacOS/test05
# Generated by qmake (3.0) (Qt 5.6.1)
# Project:  test05.pro
# Template: app
# Command: /Users/chenchaowei/Qt5.6.1/5.6/clang_64/bin/qmake -spec macx-clang CONFIG+=x86_64 -o Makefile test05.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -Wno-unused-parameter -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.7 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -Wno-unused-parameter -O2 -std=gnu++11 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.7 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I../../Qt5.6.1/5.6/clang_64/lib/QtWidgets.framework/Headers -I../../Qt5.6.1/5.6/clang_64/lib/QtGui.framework/Headers -I../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers -Iobj -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/AGL.framework/Headers -Iobj/ui_header -I../../Qt5.6.1/5.6/clang_64/mkspecs/macx-clang -F/Users/chenchaowei/Qt5.6.1/5.6/clang_64/lib
QMAKE         = /Users/chenchaowei/Qt5.6.1/5.6/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = test051.0.0
DISTDIR = /Users/chenchaowei/Desktop/test05/obj/test051.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -stdlib=libc++ -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.7 -Wl,-rpath,/Users/chenchaowei/Qt5.6.1/5.6/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/chenchaowei/Qt5.6.1/5.6/clang_64/lib -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = main.cpp \
		widget.cpp \
		StageSpeed.cpp \
		ItemRotate.cpp \
		ItemNum.cpp \
		CNum.cpp \
		StageSpeed2.cpp qrc_pic.cpp \
		obj/moc_widget.cpp \
		obj/moc_StageSpeed.cpp \
		obj/moc_ItemRotate.cpp \
		obj/moc_ItemNum.cpp \
		obj/moc_CNum.cpp \
		obj/moc_StageSpeed2.cpp
OBJECTS       = obj/main.o \
		obj/widget.o \
		obj/StageSpeed.o \
		obj/ItemRotate.o \
		obj/ItemNum.o \
		obj/CNum.o \
		obj/StageSpeed2.o \
		obj/qrc_pic.o \
		obj/moc_widget.o \
		obj/moc_StageSpeed.o \
		obj/moc_ItemRotate.o \
		obj/moc_ItemNum.o \
		obj/moc_CNum.o \
		obj/moc_StageSpeed2.o
DIST          = ../../Qt5.6.1/5.6/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt5.6.1/5.6/clang_64/mkspecs/qdevice.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/features/device_config.prf \
		../../Qt5.6.1/5.6/clang_64/mkspecs/common/unix.conf \
		../../Qt5.6.1/5.6/clang_64/mkspecs/common/mac.conf \
		../../Qt5.6.1/5.6/clang_64/mkspecs/common/macx.conf \
		../../Qt5.6.1/5.6/clang_64/mkspecs/common/sanitize.conf \
		../../Qt5.6.1/5.6/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt5.6.1/5.6/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt5.6.1/5.6/clang_64/mkspecs/common/clang.conf \
		../../Qt5.6.1/5.6/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt5.6.1/5.6/clang_64/mkspecs/qconfig.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_labscontrols_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_labstemplates_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt5.6.1/5.6/clang_64/mkspecs/features/qt_config.prf \
		../../Qt5.6.1/5.6/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt5.6.1/5.6/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt5.6.1/5.6/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt5.6.1/5.6/clang_64/mkspecs/features/default_pre.prf \
		../../Qt5.6.1/5.6/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Qt5.6.1/5.6/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt5.6.1/5.6/clang_64/mkspecs/features/default_post.prf \
		../../Qt5.6.1/5.6/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt5.6.1/5.6/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt5.6.1/5.6/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt5.6.1/5.6/clang_64/mkspecs/features/warn_on.prf \
		../../Qt5.6.1/5.6/clang_64/mkspecs/features/qt.prf \
		../../Qt5.6.1/5.6/clang_64/mkspecs/features/resources.prf \
		../../Qt5.6.1/5.6/clang_64/mkspecs/features/moc.prf \
		../../Qt5.6.1/5.6/clang_64/mkspecs/features/unix/opengl.prf \
		../../Qt5.6.1/5.6/clang_64/mkspecs/features/uic.prf \
		../../Qt5.6.1/5.6/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt5.6.1/5.6/clang_64/mkspecs/features/file_copies.prf \
		../../Qt5.6.1/5.6/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt5.6.1/5.6/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt5.6.1/5.6/clang_64/mkspecs/features/exceptions.prf \
		../../Qt5.6.1/5.6/clang_64/mkspecs/features/yacc.prf \
		../../Qt5.6.1/5.6/clang_64/mkspecs/features/lex.prf \
		test05.pro widget.h \
		StageSpeed.h \
		ItemRotate.h \
		ItemNum.h \
		CNum.h \
		StageSpeed2.h main.cpp \
		widget.cpp \
		StageSpeed.cpp \
		ItemRotate.cpp \
		ItemNum.cpp \
		CNum.cpp \
		StageSpeed2.cpp
QMAKE_TARGET  = test05
DESTDIR       = ../bin/
TARGET        = ../bin/test05.app/Contents/MacOS/test05


first: all
####### Build rules

$(TARGET): obj/ui_header/ui_widget.h obj/ui_header/ui_StageSpeed.h obj/ui_header/ui_ItemNum.h obj/ui_header/ui_CNum.h obj/ui_header/ui_StageSpeed2.h $(OBJECTS)  
	@test -d ../bin/test05.app/Contents/MacOS/ || mkdir -p ../bin/test05.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: test05.pro ../../Qt5.6.1/5.6/clang_64/mkspecs/macx-clang/qmake.conf ../../Qt5.6.1/5.6/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt5.6.1/5.6/clang_64/mkspecs/qdevice.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/features/device_config.prf \
		../../Qt5.6.1/5.6/clang_64/mkspecs/common/unix.conf \
		../../Qt5.6.1/5.6/clang_64/mkspecs/common/mac.conf \
		../../Qt5.6.1/5.6/clang_64/mkspecs/common/macx.conf \
		../../Qt5.6.1/5.6/clang_64/mkspecs/common/sanitize.conf \
		../../Qt5.6.1/5.6/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt5.6.1/5.6/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt5.6.1/5.6/clang_64/mkspecs/common/clang.conf \
		../../Qt5.6.1/5.6/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt5.6.1/5.6/clang_64/mkspecs/qconfig.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_labscontrols_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_labstemplates_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt5.6.1/5.6/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt5.6.1/5.6/clang_64/mkspecs/features/qt_config.prf \
		../../Qt5.6.1/5.6/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt5.6.1/5.6/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt5.6.1/5.6/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt5.6.1/5.6/clang_64/mkspecs/features/default_pre.prf \
		../../Qt5.6.1/5.6/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Qt5.6.1/5.6/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt5.6.1/5.6/clang_64/mkspecs/features/default_post.prf \
		../../Qt5.6.1/5.6/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt5.6.1/5.6/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt5.6.1/5.6/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt5.6.1/5.6/clang_64/mkspecs/features/warn_on.prf \
		../../Qt5.6.1/5.6/clang_64/mkspecs/features/qt.prf \
		../../Qt5.6.1/5.6/clang_64/mkspecs/features/resources.prf \
		../../Qt5.6.1/5.6/clang_64/mkspecs/features/moc.prf \
		../../Qt5.6.1/5.6/clang_64/mkspecs/features/unix/opengl.prf \
		../../Qt5.6.1/5.6/clang_64/mkspecs/features/uic.prf \
		../../Qt5.6.1/5.6/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt5.6.1/5.6/clang_64/mkspecs/features/file_copies.prf \
		../../Qt5.6.1/5.6/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt5.6.1/5.6/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt5.6.1/5.6/clang_64/mkspecs/features/exceptions.prf \
		../../Qt5.6.1/5.6/clang_64/mkspecs/features/yacc.prf \
		../../Qt5.6.1/5.6/clang_64/mkspecs/features/lex.prf \
		test05.pro \
		res/pic.qrc \
		../../Qt5.6.1/5.6/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		../../Qt5.6.1/5.6/clang_64/lib/QtGui.framework/QtGui.prl \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec macx-clang CONFIG+=x86_64 -o Makefile test05.pro
../../Qt5.6.1/5.6/clang_64/mkspecs/features/spec_pre.prf:
../../Qt5.6.1/5.6/clang_64/mkspecs/qdevice.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/features/device_config.prf:
../../Qt5.6.1/5.6/clang_64/mkspecs/common/unix.conf:
../../Qt5.6.1/5.6/clang_64/mkspecs/common/mac.conf:
../../Qt5.6.1/5.6/clang_64/mkspecs/common/macx.conf:
../../Qt5.6.1/5.6/clang_64/mkspecs/common/sanitize.conf:
../../Qt5.6.1/5.6/clang_64/mkspecs/common/gcc-base.conf:
../../Qt5.6.1/5.6/clang_64/mkspecs/common/gcc-base-mac.conf:
../../Qt5.6.1/5.6/clang_64/mkspecs/common/clang.conf:
../../Qt5.6.1/5.6/clang_64/mkspecs/common/clang-mac.conf:
../../Qt5.6.1/5.6/clang_64/mkspecs/qconfig.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_core.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_help.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_labscontrols_private.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_labstemplates_private.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_location.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_network.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_script.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Qt5.6.1/5.6/clang_64/mkspecs/features/qt_functions.prf:
../../Qt5.6.1/5.6/clang_64/mkspecs/features/qt_config.prf:
../../Qt5.6.1/5.6/clang_64/mkspecs/macx-clang/qmake.conf:
../../Qt5.6.1/5.6/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../Qt5.6.1/5.6/clang_64/mkspecs/features/exclusive_builds.prf:
../../Qt5.6.1/5.6/clang_64/mkspecs/features/default_pre.prf:
../../Qt5.6.1/5.6/clang_64/mkspecs/features/mac/default_pre.prf:
../../Qt5.6.1/5.6/clang_64/mkspecs/features/resolve_config.prf:
../../Qt5.6.1/5.6/clang_64/mkspecs/features/default_post.prf:
../../Qt5.6.1/5.6/clang_64/mkspecs/features/mac/sdk.prf:
../../Qt5.6.1/5.6/clang_64/mkspecs/features/mac/default_post.prf:
../../Qt5.6.1/5.6/clang_64/mkspecs/features/mac/objective_c.prf:
../../Qt5.6.1/5.6/clang_64/mkspecs/features/warn_on.prf:
../../Qt5.6.1/5.6/clang_64/mkspecs/features/qt.prf:
../../Qt5.6.1/5.6/clang_64/mkspecs/features/resources.prf:
../../Qt5.6.1/5.6/clang_64/mkspecs/features/moc.prf:
../../Qt5.6.1/5.6/clang_64/mkspecs/features/unix/opengl.prf:
../../Qt5.6.1/5.6/clang_64/mkspecs/features/uic.prf:
../../Qt5.6.1/5.6/clang_64/mkspecs/features/unix/thread.prf:
../../Qt5.6.1/5.6/clang_64/mkspecs/features/file_copies.prf:
../../Qt5.6.1/5.6/clang_64/mkspecs/features/mac/rez.prf:
../../Qt5.6.1/5.6/clang_64/mkspecs/features/testcase_targets.prf:
../../Qt5.6.1/5.6/clang_64/mkspecs/features/exceptions.prf:
../../Qt5.6.1/5.6/clang_64/mkspecs/features/yacc.prf:
../../Qt5.6.1/5.6/clang_64/mkspecs/features/lex.prf:
test05.pro:
res/pic.qrc:
../../Qt5.6.1/5.6/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
../../Qt5.6.1/5.6/clang_64/lib/QtGui.framework/QtGui.prl:
../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=x86_64 -o Makefile test05.pro

qmake_all: FORCE

../bin/test05.app/Contents/PkgInfo: 
	@test -d ../bin/test05.app/Contents || mkdir -p ../bin/test05.app/Contents
	@$(DEL_FILE) ../bin/test05.app/Contents/PkgInfo
	@echo "APPL????" > ../bin/test05.app/Contents/PkgInfo
../bin/test05.app/Contents/Resources/empty.lproj: 
	@test -d ../bin/test05.app/Contents/Resources || mkdir -p ../bin/test05.app/Contents/Resources
	@touch ../bin/test05.app/Contents/Resources/empty.lproj
	
../bin/test05.app/Contents/Info.plist: 
	@test -d ../bin/test05.app/Contents || mkdir -p ../bin/test05.app/Contents
	@$(DEL_FILE) ../bin/test05.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,RogerProject.test05,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,test05,g" -e "s,@LIBRARY@,test05,g" -e "s,@TYPEINFO@,????,g" ../../Qt5.6.1/5.6/clang_64/mkspecs/macx-clang/Info.plist.app >../bin/test05.app/Contents/Info.plist

all: Makefile \
		../bin/test05.app/Contents/PkgInfo \
		../bin/test05.app/Contents/Resources/empty.lproj \
		../bin/test05.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents res/pic.qrc $(DISTDIR)/
	$(COPY_FILE) --parents widget.h StageSpeed.h ItemRotate.h ItemNum.h CNum.h StageSpeed2.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp widget.cpp StageSpeed.cpp ItemRotate.cpp ItemNum.cpp CNum.cpp StageSpeed2.cpp $(DISTDIR)/
	$(COPY_FILE) --parents widget.ui StageSpeed.ui ItemNum.ui CNum.ui StageSpeed2.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r ../bin/test05.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_pic.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_pic.cpp
qrc_pic.cpp: res/pic.qrc \
		res/bBg.png \
		res/bgL_0.png \
		res/bgL_1.png \
		res/bgL_2.png \
		res/bA.png \
		res/demoV3_0.png \
		res/bBg2_0.png \
		res/bBg2_1.png \
		res/bBg2_2.png \
		res/bBg2_3.png \
		res/bBg2_4.png \
		res/bBg2_5.png \
		res/bBg2_6.png \
		res/bBg2_7.png \
		res/c0.png \
		res/c1.png \
		res/c2.png \
		res/bBg2.png \
		res/Real_Demo_V3.png
	/Users/chenchaowei/Qt5.6.1/5.6/clang_64/bin/rcc -name pic res/pic.qrc -o qrc_pic.cpp

compiler_moc_header_make_all: obj/moc_widget.cpp obj/moc_StageSpeed.cpp obj/moc_ItemRotate.cpp obj/moc_ItemNum.cpp obj/moc_CNum.cpp obj/moc_StageSpeed2.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) obj/moc_widget.cpp obj/moc_StageSpeed.cpp obj/moc_ItemRotate.cpp obj/moc_ItemNum.cpp obj/moc_CNum.cpp obj/moc_StageSpeed2.cpp
obj/moc_widget.cpp: ../../Qt5.6.1/5.6/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Qt5.6.1/5.6/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtGui.framework/Headers/QPaintEvent \
		../../Qt5.6.1/5.6/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../Qt5.6.1/5.6/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		StageSpeed.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtGui.framework/Headers/QResizeEvent \
		ItemRotate.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/QTime \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/qdatetime.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/QSize \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/qsize.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/QTimerEvent \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/qcoreevent.h \
		widget.h
	/Users/chenchaowei/Qt5.6.1/5.6/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/chenchaowei/Qt5.6.1/5.6/clang_64/mkspecs/macx-clang -I/Users/chenchaowei/Desktop/test05 -I/Users/chenchaowei/Qt5.6.1/5.6/clang_64/lib/QtWidgets.framework/Headers -I/Users/chenchaowei/Qt5.6.1/5.6/clang_64/lib/QtGui.framework/Headers -I/Users/chenchaowei/Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers -F/Users/chenchaowei/Qt5.6.1/5.6/clang_64/lib widget.h -o obj/moc_widget.cpp

obj/moc_StageSpeed.cpp: ../../Qt5.6.1/5.6/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Qt5.6.1/5.6/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtGui.framework/Headers/QResizeEvent \
		../../Qt5.6.1/5.6/clang_64/lib/QtGui.framework/Headers/qevent.h \
		ItemRotate.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtGui.framework/Headers/QPaintEvent \
		../../Qt5.6.1/5.6/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../Qt5.6.1/5.6/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/QTime \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/qdatetime.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/QSize \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/qsize.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/QTimerEvent \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/qcoreevent.h \
		StageSpeed.h
	/Users/chenchaowei/Qt5.6.1/5.6/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/chenchaowei/Qt5.6.1/5.6/clang_64/mkspecs/macx-clang -I/Users/chenchaowei/Desktop/test05 -I/Users/chenchaowei/Qt5.6.1/5.6/clang_64/lib/QtWidgets.framework/Headers -I/Users/chenchaowei/Qt5.6.1/5.6/clang_64/lib/QtGui.framework/Headers -I/Users/chenchaowei/Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers -F/Users/chenchaowei/Qt5.6.1/5.6/clang_64/lib StageSpeed.h -o obj/moc_StageSpeed.cpp

obj/moc_ItemRotate.cpp: ../../Qt5.6.1/5.6/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Qt5.6.1/5.6/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtGui.framework/Headers/QPaintEvent \
		../../Qt5.6.1/5.6/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../Qt5.6.1/5.6/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/QTime \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/qdatetime.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/QSize \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/qsize.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtGui.framework/Headers/QResizeEvent \
		ItemRotate.h
	/Users/chenchaowei/Qt5.6.1/5.6/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/chenchaowei/Qt5.6.1/5.6/clang_64/mkspecs/macx-clang -I/Users/chenchaowei/Desktop/test05 -I/Users/chenchaowei/Qt5.6.1/5.6/clang_64/lib/QtWidgets.framework/Headers -I/Users/chenchaowei/Qt5.6.1/5.6/clang_64/lib/QtGui.framework/Headers -I/Users/chenchaowei/Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers -F/Users/chenchaowei/Qt5.6.1/5.6/clang_64/lib ItemRotate.h -o obj/moc_ItemRotate.cpp

obj/moc_ItemNum.cpp: ../../Qt5.6.1/5.6/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Qt5.6.1/5.6/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtGui.framework/Headers/QResizeEvent \
		../../Qt5.6.1/5.6/clang_64/lib/QtGui.framework/Headers/qevent.h \
		ItemNum.h
	/Users/chenchaowei/Qt5.6.1/5.6/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/chenchaowei/Qt5.6.1/5.6/clang_64/mkspecs/macx-clang -I/Users/chenchaowei/Desktop/test05 -I/Users/chenchaowei/Qt5.6.1/5.6/clang_64/lib/QtWidgets.framework/Headers -I/Users/chenchaowei/Qt5.6.1/5.6/clang_64/lib/QtGui.framework/Headers -I/Users/chenchaowei/Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers -F/Users/chenchaowei/Qt5.6.1/5.6/clang_64/lib ItemNum.h -o obj/moc_ItemNum.cpp

obj/moc_CNum.cpp: ../../Qt5.6.1/5.6/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Qt5.6.1/5.6/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		CNum.h
	/Users/chenchaowei/Qt5.6.1/5.6/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/chenchaowei/Qt5.6.1/5.6/clang_64/mkspecs/macx-clang -I/Users/chenchaowei/Desktop/test05 -I/Users/chenchaowei/Qt5.6.1/5.6/clang_64/lib/QtWidgets.framework/Headers -I/Users/chenchaowei/Qt5.6.1/5.6/clang_64/lib/QtGui.framework/Headers -I/Users/chenchaowei/Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers -F/Users/chenchaowei/Qt5.6.1/5.6/clang_64/lib CNum.h -o obj/moc_CNum.cpp

obj/moc_StageSpeed2.cpp: ../../Qt5.6.1/5.6/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Qt5.6.1/5.6/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		StageSpeed2.h
	/Users/chenchaowei/Qt5.6.1/5.6/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/chenchaowei/Qt5.6.1/5.6/clang_64/mkspecs/macx-clang -I/Users/chenchaowei/Desktop/test05 -I/Users/chenchaowei/Qt5.6.1/5.6/clang_64/lib/QtWidgets.framework/Headers -I/Users/chenchaowei/Qt5.6.1/5.6/clang_64/lib/QtGui.framework/Headers -I/Users/chenchaowei/Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers -F/Users/chenchaowei/Qt5.6.1/5.6/clang_64/lib StageSpeed2.h -o obj/moc_StageSpeed2.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: obj/ui_header/ui_widget.h obj/ui_header/ui_StageSpeed.h obj/ui_header/ui_ItemNum.h obj/ui_header/ui_CNum.h obj/ui_header/ui_StageSpeed2.h
compiler_uic_clean:
	-$(DEL_FILE) obj/ui_header/ui_widget.h obj/ui_header/ui_StageSpeed.h obj/ui_header/ui_ItemNum.h obj/ui_header/ui_CNum.h obj/ui_header/ui_StageSpeed2.h
obj/ui_header/ui_widget.h: widget.ui \
		StageSpeed.h \
		StageSpeed2.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Qt5.6.1/5.6/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtGui.framework/Headers/QResizeEvent \
		../../Qt5.6.1/5.6/clang_64/lib/QtGui.framework/Headers/qevent.h \
		ItemRotate.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtGui.framework/Headers/QPaintEvent \
		../../Qt5.6.1/5.6/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../Qt5.6.1/5.6/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/QTime \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/qdatetime.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/QSize \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/qsize.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/QTimerEvent \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/qcoreevent.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Qt5.6.1/5.6/clang_64/lib/QtWidgets.framework/Headers/qwidget.h
	/Users/chenchaowei/Qt5.6.1/5.6/clang_64/bin/uic widget.ui -o obj/ui_header/ui_widget.h

obj/ui_header/ui_StageSpeed.h: StageSpeed.ui \
		ItemNum.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Qt5.6.1/5.6/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtGui.framework/Headers/QResizeEvent \
		../../Qt5.6.1/5.6/clang_64/lib/QtGui.framework/Headers/qevent.h
	/Users/chenchaowei/Qt5.6.1/5.6/clang_64/bin/uic StageSpeed.ui -o obj/ui_header/ui_StageSpeed.h

obj/ui_header/ui_ItemNum.h: ItemNum.ui \
		CNum.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Qt5.6.1/5.6/clang_64/lib/QtWidgets.framework/Headers/qwidget.h
	/Users/chenchaowei/Qt5.6.1/5.6/clang_64/bin/uic ItemNum.ui -o obj/ui_header/ui_ItemNum.h

obj/ui_header/ui_CNum.h: CNum.ui
	/Users/chenchaowei/Qt5.6.1/5.6/clang_64/bin/uic CNum.ui -o obj/ui_header/ui_CNum.h

obj/ui_header/ui_StageSpeed2.h: StageSpeed2.ui
	/Users/chenchaowei/Qt5.6.1/5.6/clang_64/bin/uic StageSpeed2.ui -o obj/ui_header/ui_StageSpeed2.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

obj/main.o: main.cpp widget.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Qt5.6.1/5.6/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtGui.framework/Headers/QPaintEvent \
		../../Qt5.6.1/5.6/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../Qt5.6.1/5.6/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		StageSpeed.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtGui.framework/Headers/QResizeEvent \
		ItemRotate.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/QTime \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/qdatetime.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/QSize \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/qsize.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/QTimerEvent \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/qcoreevent.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../Qt5.6.1/5.6/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtWidgets.framework/Headers/QDesktopWidget \
		../../Qt5.6.1/5.6/clang_64/lib/QtWidgets.framework/Headers/qdesktopwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o main.cpp

obj/widget.o: widget.cpp widget.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Qt5.6.1/5.6/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtGui.framework/Headers/QPaintEvent \
		../../Qt5.6.1/5.6/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../Qt5.6.1/5.6/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		StageSpeed.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtGui.framework/Headers/QResizeEvent \
		ItemRotate.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/QTime \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/qdatetime.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/QSize \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/qsize.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/QTimerEvent \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/qcoreevent.h \
		obj/ui_header/ui_widget.h \
		StageSpeed2.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/widget.o widget.cpp

obj/StageSpeed.o: StageSpeed.cpp StageSpeed.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Qt5.6.1/5.6/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtGui.framework/Headers/QResizeEvent \
		../../Qt5.6.1/5.6/clang_64/lib/QtGui.framework/Headers/qevent.h \
		ItemRotate.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtGui.framework/Headers/QPaintEvent \
		../../Qt5.6.1/5.6/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../Qt5.6.1/5.6/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/QTime \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/qdatetime.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/QSize \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/qsize.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/QTimerEvent \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/qcoreevent.h \
		obj/ui_header/ui_StageSpeed.h \
		ItemNum.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/StageSpeed.o StageSpeed.cpp

obj/ItemRotate.o: ItemRotate.cpp ItemRotate.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Qt5.6.1/5.6/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtGui.framework/Headers/QPaintEvent \
		../../Qt5.6.1/5.6/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../Qt5.6.1/5.6/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/QTime \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/qdatetime.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/QSize \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/qsize.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../Qt5.6.1/5.6/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtGui.framework/Headers/QResizeEvent
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/ItemRotate.o ItemRotate.cpp

obj/ItemNum.o: ItemNum.cpp ItemNum.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Qt5.6.1/5.6/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtGui.framework/Headers/QResizeEvent \
		../../Qt5.6.1/5.6/clang_64/lib/QtGui.framework/Headers/qevent.h \
		obj/ui_header/ui_ItemNum.h \
		CNum.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/ItemNum.o ItemNum.cpp

obj/CNum.o: CNum.cpp CNum.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Qt5.6.1/5.6/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		obj/ui_header/ui_CNum.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/CNum.o CNum.cpp

obj/StageSpeed2.o: StageSpeed2.cpp StageSpeed2.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Qt5.6.1/5.6/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		obj/ui_header/ui_StageSpeed2.h \
		../../Qt5.6.1/5.6/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../Qt5.6.1/5.6/clang_64/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/StageSpeed2.o StageSpeed2.cpp

obj/qrc_pic.o: qrc_pic.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/qrc_pic.o qrc_pic.cpp

obj/moc_widget.o: obj/moc_widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_widget.o obj/moc_widget.cpp

obj/moc_StageSpeed.o: obj/moc_StageSpeed.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_StageSpeed.o obj/moc_StageSpeed.cpp

obj/moc_ItemRotate.o: obj/moc_ItemRotate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_ItemRotate.o obj/moc_ItemRotate.cpp

obj/moc_ItemNum.o: obj/moc_ItemNum.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_ItemNum.o obj/moc_ItemNum.cpp

obj/moc_CNum.o: obj/moc_CNum.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_CNum.o obj/moc_CNum.cpp

obj/moc_StageSpeed2.o: obj/moc_StageSpeed2.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_StageSpeed2.o obj/moc_StageSpeed2.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

